import type { Tool } from "../../llm/types";
import { gitPush } from ".";

interface FixedItem {
  packageName: string;
  fromVersion: string;
  toVersion: string;
  vulnsFixed: number;
}

interface ManualReviewItem {
  packageName: string;
  severity: string;
  reason: string;
}

interface PrArgs {
  branch: string;
  baseBranch: string;
  fixed: FixedItem[];
  manualReview: ManualReviewItem[];
  vulnsBefore: number;
  vulnsAfter: number;
}

function parseArgs(raw: Record<string, unknown>): PrArgs {
  const branch = String(raw.branch ?? "").trim();
  const baseBranch = String(raw.baseBranch ?? "").trim();
  if (!branch || !baseBranch) {
    throw new Error("create_pull_request requires 'branch' and 'baseBranch'");
  }
  return {
    branch,
    baseBranch,
    fixed: Array.isArray(raw.fixed) ? (raw.fixed as FixedItem[]) : [],
    manualReview: Array.isArray(raw.manualReview) ? (raw.manualReview as ManualReviewItem[]) : [],
    vulnsBefore: Number(raw.vulnsBefore ?? 0),
    vulnsAfter: Number(raw.vulnsAfter ?? 0),
  };
}

function buildBody(a: PrArgs): string {
  const lines: string[] = [];
  lines.push("## Automated dependency security fixes", "");
  lines.push(`Vulnerabilities: **${a.vulnsBefore} → ${a.vulnsAfter}** ` +
    `(${a.vulnsBefore - a.vulnsAfter} resolved)`, "");

  if (a.fixed.length) {
    lines.push("### ✅ Fixed", "");
    lines.push("| Package | Change | Vulns fixed |", "|---|---|---|");
    for (const f of a.fixed) {
      lines.push(`| \`${f.packageName}\` | ${f.fromVersion} → ${f.toVersion} | ${f.vulnsFixed} |`);
    }
    lines.push("");
  }

  if (a.manualReview.length) {
    lines.push("### ⚠️ Requires manual review", "");
    lines.push("| Package | Severity | Reason |", "|---|---|---|");
    for (const m of a.manualReview) {
      lines.push(`| \`${m.packageName}\` | ${m.severity} | ${m.reason} |`);
    }
    lines.push("");
  }

  lines.push("---", "_Generated by the Snyk remediation agent. Review before merging._");
  return lines.join("\n");
}

export function createCreatePrTool(targetDir: string): Tool {
  return {
    definition: {
      name: "create_pull_request",
      description:
        "Push the working branch and open a GitHub pull request summarizing the " +
        "dependency fixes. Call this LAST, after all upgrades are committed or reverted " +
        "and a final snyk_scan has run. Provide the fixed packages, any manual-review " +
        "items, and the before/after vulnerability counts.",
      parameters: {
        type: "object",
        properties: {
          branch: { type: "string", description: "The working branch to open the PR from." },
          baseBranch: { type: "string", description: "The branch to merge into, e.g. 'main'." },
          fixed: {
            type: "array",
            description: "Successfully committed upgrades.",
            items: {
              type: "object",
              properties: {
                packageName: { type: "string" },
                fromVersion: { type: "string" },
                toVersion: { type: "string" },
                vulnsFixed: { type: "number" },
              },
              required: ["packageName", "fromVersion", "toVersion", "vulnsFixed"],
            },
          },
          manualReview: {
            type: "array",
            description: "Vulnerabilities with no automated fix, or upgrades reverted for failing tests.",
            items: {
              type: "object",
              properties: {
                packageName: { type: "string" },
                severity: { type: "string" },
                reason: { type: "string" },
              },
              required: ["packageName", "severity", "reason"],
            },
          },
          vulnsBefore: { type: "number", description: "Total vulnerabilities before fixes." },
          vulnsAfter: { type: "number", description: "Total vulnerabilities after fixes." },
        },
        required: ["branch", "baseBranch", "vulnsBefore", "vulnsAfter"],
      },
    },
    async execute(raw: Record<string, unknown>): Promise<string> {
      let args: PrArgs;
      try {
        args = parseArgs(raw);
      } catch (err) {
        return JSON.stringify({ ok: false, stage: "args", error: (err as Error).message });
      }

      const token = process.env.GITHUB_TOKEN;
      const repo = process.env.GITHUB_REPO;
      if (!token || !repo) {
        return JSON.stringify({
          ok: false, stage: "config",
          error: "GITHUB_TOKEN and GITHUB_REPO must be set in the environment",
        });
      }

      // 1. Push the branch so GitHub can see it.
      try {
        await gitPush(targetDir, args.branch);
      } catch (err) {
        return JSON.stringify({ ok: false, stage: "push", error: (err as Error).message });
      }

      // 2. Open the PR via REST.
      const title =
        args.fixed.length
          ? `fix(deps): resolve ${args.vulnsBefore - args.vulnsAfter} vulnerabilities`
          : "chore(deps): dependency security review";

      const res = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          head: args.branch,
          base: args.baseBranch,
          body: buildBody(args),
        }),
      });

      const data = (await res.json()) as { html_url?: string; message?: string };
      if (!res.ok) {
        return JSON.stringify({
          ok: false, stage: "github", status: res.status,
          error: data.message ?? "GitHub API error",
        });
      }
      return JSON.stringify({ ok: true, pullRequestUrl: data.html_url });
    },
  };
}